name: Check code quality

on:
  pull_request:
    branches: [ "main" ]

permission:
  contents: read

env:
   FILES_TO_CHECK: 'app'
   BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'poetry'
      - run: poetry install --only main

      - name: Start procesing Linters for code quality
        run: |
          poetry install --only linters,formatters
          
          poetry run flake8 ${{ env.FILES_TO_CHECK }}
          poetry run black --check ${{ env.FILES_TO_CHECK }}
          poetry run pylint ${{ env.FILES_TO_CHECK }}